title = "Hey there, friend ğŸ‘‹"
subtitle = "Thanks for stopping by. My name is Britton Hayes and I'd love to collaborate with you on any of my projects so please feel free to open a PR. :heart:"
file = "README.md"

[sections]
    [sections.about]
    title = "About ğŸ“˜"
    subtitle = "A bit about me"
    items = [
        "ğŸ”­ I'm currently working on [inventory](https://github.com/open-farms/inventory), [pillager](https://github.com/brittonhayes/pillager), and [hikeshi](https://github.com/brittonhayes/hikeshi)",
        "â­ I'm a big fan of Fish, Terraform, and [Go](https://golang.org) (as you can probably tell by the Gophers and Go repos everywhere)",
        "ğŸ¤ I'm looking to collaborate on my credential [pillager](https://github.com/brittonhayes/pillager)",
        "ğŸ¤” I'm usually researching Kubernetes security monitoring",
        "ğŸ’¬ Ask me how to make a sweet base in [Satisfactory](https://www.satisfactorygame.com/)",
        "ğŸ˜„ Pronouns: [he/him](https://pronoun.is/he)"
    ]
    
    [sections.activity]
    title = "Activity âš¡"
    subtitle = "What I've been up to"
    images = [
        "![Britton's Github Stats](https://github-readme-stats.vercel.app/api?username=brittonhayes&show_icons=true&count_private=true&title_color=95c4ce&icon_color=95c4ce&text_color=c6c8d1&bg_color=161821)",
        "![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=brittonhayes&hide=javascript,html,css&title_color=95c4ce&icon_color=95c4ce&text_color=c6c8d1&bg_color=161821)",
    ]

    [sections.projects]
    title = "Finds ğŸ”¬"
    subtitle = "A few projects I'm excited about"
    images = [
        "![ReadMe Card](https://github-readme-stats.vercel.app/api/pin/?username=princjef&repo=gomarkdoc&title_color=95c4ce&icon_color=95c4ce&text_color=c6c8d1&bg_color=161821)",
        "![ReadMe Card](https://github-readme-stats.vercel.app/api/pin/?username=BurntSushi&repo=ripgrep&title_color=95c4ce&icon_color=95c4ce&text_color=c6c8d1&bg_color=161821)",
    ]